### ISSUE TITLE
Dev API Gateway not passing through URL query params

### ISSUE THREAD

**Issue by sleelin** [nitrictech/dev-api-gateway#3]
**Environment:**
**OS:** MacOS 11.6.3 (Intel)
**Nitric CLI:** @nitric/cli/0.2.0-rc.6b54497d darwin-x64 node-v16.13.0
**Nitric SDK:** v0.2.2

**Issue:**
It seems like the dev API gateway isn't forwarding query string params through to the function containers.

When I make a request with a query string through the gateway, hitting URL `http://localhost:49152/private/task?n=10`, logging shows that the query object is empty:
```ts
HttpRequest {
  data: '',
  method: 'GET',
  path: '/private/tasks',
  query: {},
  headers: {
    accept: '*/*',
    'accept-encoding': 'gzip, deflate, br',
    'cache-control': 'no-cache',
    connection: 'keep-alive',
    'content-length': '0',
    'postman-token': '03a4ff48-dd8b-418b-83ee-bae0ef98b645',
    'user-agent': 'PostmanRuntime/7.29.0',
    'x-forwarded-for': 'apiservice-private-task:9001'
  }
}
```

When I make the same request directly to the function container endpoint, hitting URL `http://localhost:64644/?n=10`, logging shows that the query object has been populated correctly:
```ts
HttpRequest {
  data: '',
  method: 'GET',
  path: '',
  query: { n: '10' },
  headers: {
    accept: '*/*',
    'accept-encoding': 'gzip, deflate, br',
    'cache-control': 'no-cache',
    connection: 'keep-alive',
    'content-length': '0',
    'postman-token': '1fc5b845-04c4-440c-ae6e-6dcc7a04fcf8',
    'user-agent': 'PostmanRuntime/7.29.0',
    'x-forwarded-for': 'localhost:64644'
  }
}
```

I believe I have traced the issue to the following line in the main file, which is only passing in `r.URL.Path` in the passthrough request:
https://github.com/nitrictech/dev-api-gateway/blob/97898e10c762c097a703120df14d095d114b9f08/main.go#L39

Should this also be capturing the `r.URL.RawQuery` value to be passed through?

For reference, the relevant section of the OpenAPI spec file:
```yaml
paths:
  /private/tasks:
    get:
      description: Retrieve a list of all tasks
      tags:
        - task
      operationId: private-task-read-many
      x-nitric-target:
        name: apiservice-private-task
        type: container
      parameters:
        - name: n
          in: query
          description: Count of records to return during list retrieval
          required: false
          schema:
            type: number
```
